//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.ScanerDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public long Id { get; set; }
        public long TubeId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    }
}
