//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.ScanerDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanerTubeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScanerTubeInfo()
        {
            this.Defects = new HashSet<Defect>();
        }
    
        public long id { get; set; }
        public System.DateTime Date { get; set; }
        public string Melt { get; set; }
        public string TubeNum { get; set; }
        public long TubeStatus { get; set; }
        public string TypeSize { get; set; }
        public string Standart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect> Defects { get; set; }
    }
}
