//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDT6TubeInfo : TubeInfo
    {
        public string DefectMap { get; set; }
    }
}
