//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TubeInfo
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string WorkArea { get; set; }
        public string Defectoscope { get; set; }
        public string Melt { get; set; }
        public long TubeNum { get; set; }
        public int Level { get; set; }
        public double Diameter { get; set; }
        public double Thickness { get; set; }
        public string Standart { get; set; }
    }
}
