//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.MDT6DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Melt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Melt()
        {
            this.Tubes = new HashSet<Tube>();
        }
    
        public short id_melt { get; set; }
        public System.DateTime mCreatedDate { get; set; }
        public string melt { get; set; }
        public string name_control_sample { get; set; }
        public short summ_tubes { get; set; }
        public short summ_brak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tube> Tubes { get; set; }
        public virtual Standart Standart { get; set; }
        public virtual Typesize Typesize { get; set; }
    }
}
