//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.TPC1.UNSK.Defects.MDT6DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tube
    {
        public int id_tube { get; set; }
        public System.DateTime tCreatedDate { get; set; }
        public short shift { get; set; }
        public short num_tube_shift { get; set; }
        public short num_tube_melt { get; set; }
        public string s_map_defects { get; set; }
        public short speedt { get; set; }
        public int lent { get; set; }
        public string note { get; set; }
        public Nullable<int> setting { get; set; }
        public Nullable<int> defects { get; set; }
    
        public virtual Melt Melt { get; set; }
    }
}
